#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Remove time folders
rm -rf [0-9]*

# Remove generated mesh
rm -rf constant/porousMat/polyMesh

# Remove generated plots
rm -f plots/*.pdf

# Remove processor directories
rm -rf processor*

# Remove temporary files
find . -name '*~' -delete
