#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# -----------------------------------------------------------------------------
# Initial conditions
# -----------------------------------------------------------------------------

rm -rf 0
cp -r origin.0 0

# -----------------------------------------------------------------------------
# Mesh generation
# -----------------------------------------------------------------------------

# Generate the background mesh
blockMesh -region porousMat

# Run snappyHexMesh
mv constant/porousMat/polyMesh constant/polyMesh
snappyHexMesh -overwrite
mv constant/polyMesh constant/porousMat/polyMesh

# -----------------------------------------------------------------------------
# Check final mesh
# -----------------------------------------------------------------------------

checkMesh -allGeometry -allTopology

# -----------------------------------------------------------------------------
# PATO
# -----------------------------------------------------------------------------

PATOx

# -----------------------------------------------------------------------------
