#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# -----------------------------------------------------------------------------
# Initial conditions
# -----------------------------------------------------------------------------

rm -rf 0
cp -r origin.0 0

# -----------------------------------------------------------------------------
# Mesh generation
# -----------------------------------------------------------------------------

# Generate blockMeshDict from the m4 template
m4 cylinderMesh.m4 > system/blockMeshDict

# Generate the background mesh
blockMesh

# Run snappyHexMesh
snappyHexMesh -overwrite

# -----------------------------------------------------------------------------
# PATO
# -----------------------------------------------------------------------------

PATOx

# -----------------------------------------------------------------------------
