#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# -----------------------------------------------------------------------------
# Initial conditions
# -----------------------------------------------------------------------------

rm -rf 0
cp -r origin.0 0

# -----------------------------------------------------------------------------
# Mesh generation
# -----------------------------------------------------------------------------

# Generate the background mesh
blockMesh -region porousMat

# Run snappyHexMesh
mv constant/porousMat/polyMesh constant/polyMesh
snappyHexMesh -overwrite
mv constant/polyMesh constant/porousMat/polyMesh

# -----------------------------------------------------------------------------
# Check final mesh
# -----------------------------------------------------------------------------

checkMesh -allGeometry -allTopology -region porousMat

# Check number of processors
if [ -z $1 ];
then
    echo "error: correct usage = ./Allrun_parallel <number_processors>"
    exit 1
fi
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: First argument is not a number" >&2
   exit 1
fi

NPROCESSOR=$1

# decompose the mesh                                                                                                          
decomposePar -region porousMat

#run case
mpiexec -np $NPROCESSOR PATOx -parallel

# 3D post-processing
# reconstructPar -region porousMat
# reconstructPar -region subMat1 
# paraFoam -builtin
